#!/usr/bin/env bash
# gen-pinned-requirements.sh — regenerate the hash-pinned CI/release/docs
# requirements files (SC.S1, OpenSSF Scorecard Pinned-Dependencies).
#
# WHAT THIS IS FOR
#   The CI, release and docs workflows install a handful of *tooling* packages
#   (pyyaml for the workflow-lint tests, jsonschema for the [schema] extra leg,
#   build + cyclonedx-bom for the release SBOM, mkdocs + mkdocs-material for the
#   docs site). Scorecard's Pinned-Dependencies check flags any `pip install`
#   that is not hash-pinned. This script compiles the loose `.in` inputs into
#   fully hash-pinned `.txt` files that every workflow installs with
#   `pip install --require-hashes -r requirements/<file>.txt`.
#
#   This does NOT touch mokata's own dependencies or what ships in the wheel.
#   `pip install -e .` (the editable/local install of mokata itself) is
#   deliberately NOT routed through these files — see requirements/README.md.
#
# SOURCE OF TRUTH
#   uv.lock governs mokata's own dependency graph; requirements/jsonschema.in is
#   pinned to the EXACT jsonschema version uv.lock resolves (4.26.0 for the
#   python >= 3.10 floor). The CI/build/docs tooling is not part of mokata's
#   dependency graph, so it lives in the `.in` files here and is compiled with
#   the same `uv` toolchain. Bump a version by editing the `.in`, then re-run
#   this script and commit the regenerated `.txt`.
#
# REQUIREMENTS
#   uv (https://docs.astral.sh/uv/). Install with `pipx install uv` or
#   `curl -LsSf https://astral.sh/uv/install.sh | sh`.
#
# USAGE
#   scripts/gen-pinned-requirements.sh          # regenerate all four files
#   UV=/path/to/uv scripts/gen-pinned-requirements.sh
set -euo pipefail

UV="${UV:-uv}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REQ_DIR="${REPO_ROOT}/requirements"

command -v "$UV" >/dev/null 2>&1 || {
  echo "ERROR: 'uv' not found. Install it (pipx install uv) or set UV=/path/to/uv." >&2
  exit 1
}

# Run from the repo root and pass RELATIVE paths so the autogenerated header uv
# writes into each .txt is portable (no machine-specific absolute path).
cd "$REPO_ROOT"

# --universal + --python-version 3.10 → one file valid across the whole CI matrix
# (python 3.10–3.13, Linux + Windows). --generate-hashes emits sha256 for every
# candidate wheel + sdist so `pip --require-hashes` can verify whichever it picks.
compile_one() {
  local name="$1"
  echo "== compiling requirements/${name}.txt =="
  "$UV" pip compile \
    --quiet \
    --universal \
    --python-version 3.10 \
    --generate-hashes \
    --no-annotate \
    --emit-index-url \
    "requirements/${name}.in" \
    -o "requirements/${name}.txt"
}

for f in ci jsonschema release-build docs; do
  compile_one "$f"
done

echo "OK — regenerated hash-pinned requirements under requirements/ (via uv $("$UV" --version | awk '{print $2}'))."
