"""mokata memory layer (Part C) — persistent, self-healing, default-on, human-gated.

Memory is a native part of the framework, on by default, with per-type toggles. It is
durable and pluggable (SQLite default / Obsidian / native-memory — storage only; the
logic is mokata's own), heals by SURFACING contradictions and staleness for human
approval (never silent rewrite), and gates every durable write. The memory triad —
persistent (C1), decision (C2), episodic (C3) — is individually toggleable. Consolidation
(C7) is proposal-only and human-gated; it never auto-applies.

Public API:
  - MemoryItem + types/statuses                                   (C1/C5 model)
  - SQLiteBackend / ObsidianBackend / NativeMemoryBackend         (C4 storage)
  - MemoryStore / enabled_memory_types / select_memory_backend    (C1/C2/C6/C8/C9 logic)
  - HealingProposal / detect_issues / render_proposal             (C5 surfacing)
  - EpisodicMemory / lexical_score                                (C3 episodic)
  - ConsolidationProposal / propose_consolidations                (C7 consolidation)
"""

from .backends import (
    MemoryBackend,
    MemoryClient,
    NativeMemoryBackend,
    ObsidianBackend,
    PostgresBackend,
    PostgresUnavailable,
    SQLiteBackend,
    build_postgres_backend,
)
from .share import (
    BACKUPS_DIRNAME,
    MEMORY_SHARE_FILENAME,
    ImportResult,
    MemoryImportPlan,
    MemoryShareError,
    SHARE_KIND,
    SHARE_SCHEMA_VERSION,
    default_backup_path,
    export_memory,
    export_payload,
    import_memory,
    is_legacy_share_dest,
    load_memory_share,
    plan_memory_import,
    scan_export_item,
)
from .migrate import (
    SUPPORTED as MIGRATE_BACKENDS,
    MigrateError,
    MigrateResult,
    build_named_backend,
    migrate_memory,
)
from .embed import EMBED_DIM, HashingEmbedder, cosine, make_embedder
from .tiered import RetrievalHit, tiered_recall
from .scope import (
    CATEGORY,
    CONVENTIONAL_CATEGORIES,
    DEFAULT_SCOPE_LEVEL,
    GLOBAL,
    PERSONAL,
    PROJECT,
    SCOPE_LEVELS,
    TEAM,
    ScopeContext,
    ScopeRef,
    assert_acyclic,
    is_valid_scope,
    parent_level,
    personal_context,
    scope_depth,
    scope_path,
    on_path,
    union_read,
)
from .precedence import (
    PREFERENCE,
    SAFETY,
    Resolution,
    ResolvedEntry,
    merge_values,
    precedence_class,
    resolve,
)
from .formula import (
    applies_to,
    formula_params,
    is_formula,
    make_formula,
    recall_applicable,
    render_injection,
    template_params,
)
from .growth import (
    GROWABLE_KINDS,
    FormulaProposal,
    RetainOnSuccess,
    apply_formula_proposal,
    assert_growable,
)
from .access import (
    APPROVER,
    EDITOR,
    PROMOTION_APPROVER,
    ROLES,
    VIEWER,
    AccessPolicy,
)
from .review import (
    APPROVED,
    DRAFT,
    IN_REVIEW,
    PUBLISHED,
    REJECTED as REVIEW_REJECTED,
    REVIEW_STATES,
    can_transition,
    diff_line,
    is_terminal,
    is_valid_state,
    render_transition,
    required_approvers,
    separation_ok,
)
from .vector import (
    EmbedderStampMismatch,
    PgVectorBackend,
    VectorUnavailable,
    build_pgvector_backend,
)
from .consolidation import (
    MERGE,
    PRUNE,
    SUMMARIZE,
    ConsolidationProposal,
    propose_consolidations,
    render_consolidation,
)
from .episodic import EpisodicMemory, lexical_score
from .healing import (
    CONTRADICTION,
    STALE,
    HealingProposal,
    detect_issues,
    render_proposal,
)
from .item import (
    ACTIVE,
    ADVISORY,
    ALWAYS_ON_KINDS,
    DEFAULT_TOP_K,
    DOC_KEYS,
    DOC_SUBSYSTEM,
    DOC_VERSION_KEY,
    LEGACY_DOC_VERSION,
    MEMORY_DOC_VERSION,
    UNREADABLE_DOC_VERSION,
    MemoryDocTooNew,
    can_write_doc,
    doc_version,
    downgrade_refusal,
    BEST_PRACTICE,
    CONTEXT,
    DECISION,
    ENFORCEMENT_LEVELS,
    EPISODIC,
    FACT,
    FORMULA,
    GOVERNANCE_KINDS,
    GUARDRAIL,
    HARD,
    JIT_KINDS,
    MEMORY_KINDS,
    MEMORY_TYPES,
    PART_KINDS,
    PERSISTENT,
    REFERENCE,
    RULE,
    SOFT,
    SUPERSEDED,
    MemoryItem,
    default_enforcement,
    effective_enforcement,
    enforcement_rank,
    governance_kind,
    is_valid_enforcement,
)
from .brain import (
    always_on_lines,
    group_by_kind,
    jit_recall,
    normalize_kind,
)
from .intelligence import (
    MemoryHealth,
    RecallExplanation,
    assess_health,
    explain_recall,
    memory_health,
    why_surfaced,
)
from .store import (
    MEMORY_SETTINGS_KEY,
    HealingResult,
    MemoryDisabledError,
    MemoryError,
    MemoryStats,
    MemoryStore,
    PromoteResult,
    ReviewResult,
    ScopePromoteResult,
    WriteResult,
    build_backend,
    enabled_memory_types,
    select_memory_backend,
)

__all__ = [
    "MemoryItem",
    "PERSISTENT",
    "DECISION",
    "EPISODIC",
    "MEMORY_TYPES",
    "DEFAULT_TOP_K",
    "ACTIVE",
    "SUPERSEDED",
    "STALE",
    # D6 — the memory-DOC schema axis (distinct from teamdb's DDL axis)
    "MEMORY_DOC_VERSION",
    "LEGACY_DOC_VERSION",
    "UNREADABLE_DOC_VERSION",
    "DOC_VERSION_KEY",
    "DOC_KEYS",
    "DOC_SUBSYSTEM",
    "MemoryDocTooNew",
    "doc_version",
    "can_write_doc",
    "downgrade_refusal",
    # Stage 36 — typed-memory parts (the project brain)
    "RULE",
    "GUARDRAIL",
    "BEST_PRACTICE",
    "CONTEXT",
    "REFERENCE",
    "MEMORY_KINDS",
    "PART_KINDS",
    "ALWAYS_ON_KINDS",
    "JIT_KINDS",
    "group_by_kind",
    "always_on_lines",
    "jit_recall",
    "normalize_kind",
    "MemoryBackend",
    "SQLiteBackend",
    "ObsidianBackend",
    "NativeMemoryBackend",
    "PostgresBackend",
    "PostgresUnavailable",
    "build_postgres_backend",
    "MemoryClient",
    "MemoryStore",
    "MemoryStats",
    "WriteResult",
    "HealingResult",
    "MemoryError",
    "MemoryDisabledError",
    "enabled_memory_types",
    "select_memory_backend",
    "build_backend",
    "MEMORY_SETTINGS_KEY",
    "HealingProposal",
    "detect_issues",
    "render_proposal",
    "CONTRADICTION",
    # C3 — episodic
    "EpisodicMemory",
    "lexical_score",
    # C7 — consolidation (proposal-only)
    "ConsolidationProposal",
    "propose_consolidations",
    "render_consolidation",
    "MERGE",
    "SUMMARIZE",
    "PRUNE",
    # Stage 35b — memory backup surface (export=backup / import=restore)
    "SHARE_KIND",
    "SHARE_SCHEMA_VERSION",
    "export_memory",
    "export_payload",
    "import_memory",
    "plan_memory_import",
    "MemoryImportPlan",
    "load_memory_share",
    "scan_export_item",
    "ImportResult",
    "MemoryShareError",
    "MEMORY_SHARE_FILENAME",
    "BACKUPS_DIRNAME",
    "default_backup_path",
    "is_legacy_share_dest",
    # Stage 35c — migrate between backends
    "migrate_memory",
    "build_named_backend",
    "MigrateResult",
    "MigrateError",
    "MIGRATE_BACKENDS",
    # Stage 35e — vector backend + tiered semantic retrieval
    "HashingEmbedder",
    "make_embedder",
    "cosine",
    "EMBED_DIM",
    "tiered_recall",
    "RetrievalHit",
    # Stage 59 — memory intelligence (explainable retrieval + health nudge)
    "why_surfaced",
    "explain_recall",
    "RecallExplanation",
    "MemoryHealth",
    "memory_health",
    "assess_health",
    "PgVectorBackend",
    "EmbedderStampMismatch",
    "build_pgvector_backend",
    "VectorUnavailable",
    # TM.S6 — scope hierarchy + union read (doc 62 §2)
    "GLOBAL",
    "TEAM",
    "PROJECT",
    "CATEGORY",
    "PERSONAL",
    "SCOPE_LEVELS",
    "DEFAULT_SCOPE_LEVEL",
    "CONVENTIONAL_CATEGORIES",
    "ScopeRef",
    "ScopeContext",
    "scope_path",
    "scope_depth",
    "parent_level",
    "is_valid_scope",
    "assert_acyclic",
    "personal_context",
    "on_path",
    "union_read",
    # TM.S6 — precedence / merge engine (doc 62 §3)
    "PREFERENCE",
    "SAFETY",
    "Resolution",
    "ResolvedEntry",
    "resolve",
    "merge_values",
    "precedence_class",
    # TM.S7 — governance kind × enforcement binding (doc 62 §2,4)
    "FACT",
    "FORMULA",
    "GOVERNANCE_KINDS",
    "ADVISORY",
    "SOFT",
    "HARD",
    "ENFORCEMENT_LEVELS",
    "governance_kind",
    "default_enforcement",
    "effective_enforcement",
    "enforcement_rank",
    "is_valid_enforcement",
    "PromoteResult",
    # TM.S9 — formula item + applicability recall (doc 62 §2/§8)
    "make_formula",
    "is_formula",
    "formula_params",
    "template_params",
    "applies_to",
    "recall_applicable",
    "render_injection",
    # TM.S9 — retain-on-success growth (propose-only, doc 62 §5)
    "RetainOnSuccess",
    "FormulaProposal",
    "apply_formula_proposal",
    "assert_growable",
    "GROWABLE_KINDS",
    # TM.S10 — identity + scoped-consent access control (doc 52 M-1/M-2, doc 62 §6)
    "AccessPolicy",
    "ROLES",
    "VIEWER",
    "EDITOR",
    "APPROVER",
    "PROMOTION_APPROVER",
    "ScopePromoteResult",
    # TM.S11 — PM review workflow: state machine + roles + SoD (doc 62 §6)
    "DRAFT",
    "IN_REVIEW",
    "APPROVED",
    "PUBLISHED",
    "REVIEW_REJECTED",
    "REVIEW_STATES",
    "is_valid_state",
    "is_terminal",
    "can_transition",
    "separation_ok",
    "required_approvers",
    "diff_line",
    "render_transition",
    "ReviewResult",
]
